import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="overflow-x-hidden relative mx-auto" >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
