import Navbar from '@/components/Navbar'
import '@/assets/globals.css'
import Footer from '@/components/Footer'
import Fab from '@/components/Fab'
import Modal from '@/components/Modal'
import MobileMenu from '@/components/MobileMenu'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body id="anchor" className="overflow-x-hidden relative mx-auto">
        <Navbar />
        <MobileMenu />
        <Fab />
        {children}
        <Modal />
        <Footer />
      </body>
    </html>
  )
}
