export const Routes = {
  home: '/',
  store: '/store',
  brands: '/brands',
  about: '/about',
  contact: '/contact',
  survey: '/survey',
  representatives: '/representatives',
  feedback: '/feedback',
  product: '/product',
  login: '/auth/login',
  register: '/auth/register',
  profile: '/profile',
  profileOrders: '/profile/orders',
  profilePayments: '/profile/payments',
  cart: '/cart',
  checkout: '/checkout',
}
