name: Deploy to Server

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd  /opt/www/bamdad-landing
          git pull origin main
          docker system prune -af
          git diff --exit-code package.json package-lock.json yarn.lock || docker-compose build --no-cache
          docker compose up -d --force-recreate
