name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: ${{ github.event.repository.name }}
      PROJECT_PATH: /opt/www/${{ github.event.repository.name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Sync code to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "./"
        target: "/opt/www/${{ github.event.repository.name }}"
        strip_components: 1
        rm: true

    - name: Run docker-compose with traefik on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          set -e
          PROJECT_DIR="/opt/www/${{ github.event.repository.name }}"
          cd "$PROJECT_DIR"

          if command -v docker &>/dev/null && docker compose version &>/dev/null; then
            COMPOSE="docker compose"
          elif command -v docker-compose &>/dev/null; then
            COMPOSE="docker-compose"
          else
            echo "::error::Docker Compose is not installed"
            exit 1
          fi

          $COMPOSE -f docker-compose.yml down || true
          $COMPOSE -f docker-compose.yml up -d --build